version: '3.5'

services:
  containerapp-webapp:
    container_name: containerapp-webapp
    image: containerapp-webapp
    build:
      context: src/ContainerApp.WebApp
      dockerfile: Dockerfile
    environment:
      - ApiAddress=http://containerapp-todoapi
    ports:
      - 7171:80
    links:
      - containerapp-todoapi
      - containerapp-weatherapi
    depends_on:
      - containerapp-todoapi
      - containerapp-weatherapi
  containerapp-todoapi:
    container_name: containerapp-todoapi
    image: containerapp-todoapi
    links:
      - containerapp-postgresdb
    depends_on:
      - containerapp-postgresdb
    build:
      context: src/ContainerApp.TodoApi
      dockerfile: Dockerfile
    ports:
      - 7272:80
    environment:
      - MyDbContext="Server=containerapp-postgresdb;Database=TodoItem_DB;User Id=postgres;Password=postgres;"
  containerapp-postgresdb:
    container_name: containerapp-postgresdb
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresdata-volume:/var/lib/postgresql/data
volumes:
  postgresdata-volume: